#include "theme.h"

#include "world.h"

#include <QDir>
#include <QFile>
#include <QSettings>
#include <QStandardPaths>

namespace helm {

QString effectiveGtkTheme(const ThemeSpec &s) {
    if (!s.gtkTheme.isEmpty())
        return s.gtkTheme;
    return s.dark ? QStringLiteral("Adwaita-dark") : QStringLiteral("Adwaita");
}

QString gtkSettingsIni(const ThemeSpec &s) {
    QString out = QStringLiteral("[Settings]\n");
    out += QStringLiteral("gtk-application-prefer-dark-theme=%1\n").arg(s.dark ? 1 : 0);
    out += QStringLiteral("gtk-theme-name=%1\n").arg(effectiveGtkTheme(s));
    if (!s.iconTheme.isEmpty())
        out += QStringLiteral("gtk-icon-theme-name=%1\n").arg(s.iconTheme);
    return out;
}

namespace {

// Parse "#rrggbb" into 0..255 channels; false if not a 6-digit hex colour.
bool parseHex6(const QString &hex, int &r, int &g, int &b) {
    QString h = hex.trimmed();
    if (h.startsWith(QLatin1Char('#')))
        h = h.mid(1);
    if (h.size() != 6)
        return false;
    bool ok = false;
    const int v = h.toInt(&ok, 16);
    if (!ok)
        return false;
    r = (v >> 16) & 0xff;
    g = (v >> 8) & 0xff;
    b = v & 0xff;
    return true;
}

QString hex6(int r, int g, int b) {
    auto clamp = [](int c) { return c < 0 ? 0 : (c > 255 ? 255 : c); };
    return QString::asprintf("#%02x%02x%02x", clamp(r), clamp(g), clamp(b));
}

// Same luminance rule as helm::contrastText (appearance/palette.cpp): black on
// light bars, white on dark ones. Kept here so helm-theme-lib stays Core-only
// (no QColor/Qt6::Gui); test_theme asserts parity with the canonical colours.
QString contrastHex(const QString &bg) {
    int r = 0, g = 0, b = 0;
    if (!parseHex6(bg, r, g, b))
        return QStringLiteral("#ffffff");
    const double lum = 0.299 * r + 0.587 * g + 0.114 * b;
    return lum > 140 ? QStringLiteral("#000000") : QStringLiteral("#ffffff");
}

// Scale each channel by `f` (darken < 1) for subtle borders derived from a bar.
QString scaleHex(const QString &c, double f) {
    int r = 0, g = 0, b = 0;
    if (!parseHex6(c, r, g, b))
        return c;
    auto s = [f](int v) { return int(v * f + 0.5); };
    return hex6(s(r), s(g), s(b));
}

} // namespace

QString themercBody(const ThemeSpec &s) {
    const QString accent = s.accent.isEmpty() ? QStringLiteral("#3aa6c4") : s.accent;
    const QString surface = s.dark ? QStringLiteral("#0e2c34") : QStringLiteral("#f6fafb");
    const QString activeText = contrastHex(accent);
    const QString surfaceText = contrastHex(surface);
    const QString mutedText = surfaceText + QStringLiteral("99"); // #rrggbbaa, dimmed

    QString o = QStringLiteral("# Helm titlebar skin - generated by helm-theme.\n"
                               "# Do not edit; regenerated on every theme change.\n");
    // The focused titlebar is a top-lit vertical gradient: the accent at the top
    // falling to a shadowed accent at the bottom. This is the frost/bevel of the
    // decoration_art contract rendered within labwc's real capability — labwc
    // titlebar backgrounds are Solid/Gradient only (no image/nine-slice), so a
    // gradient is the achievable painterly frame. `.color` stays the accent so
    // the bar still reads as the world colour.
    o += QStringLiteral("window.active.title.bg: Gradient Vertical\n");
    o += QStringLiteral("window.active.title.bg.color: %1\n").arg(accent);
    o += QStringLiteral("window.active.title.bg.colorTo: %1\n").arg(scaleHex(accent, 0.82));
    o += QStringLiteral("window.active.label.text.color: %1\n").arg(activeText);
    o += QStringLiteral("window.active.border.color: %1\n").arg(scaleHex(accent, 0.80));
    o += QStringLiteral("window.active.button.unpressed.image.color: %1\n").arg(activeText);
    o += QStringLiteral("window.inactive.title.bg.color: %1\n").arg(surface);
    o += QStringLiteral("window.inactive.label.text.color: %1\n").arg(mutedText);
    o += QStringLiteral("window.inactive.border.color: %1\n").arg(scaleHex(surface, 0.90));
    o += QStringLiteral("window.inactive.button.unpressed.image.color: %1\n").arg(mutedText);
    o += QStringLiteral("window.titlebar.padding.width: 8\n");
    o += QStringLiteral("window.titlebar.padding.height: 6\n");
    o += QStringLiteral("window.button.width: 22\n");
    o += QStringLiteral("window.button.height: 22\n");
    o += QStringLiteral("window.button.spacing: 6\n");
    o += QStringLiteral("window.button.hover.bg.color: %1\n").arg(surfaceText + QStringLiteral("1a"));
    o += QStringLiteral("window.button.hover.bg.corner-radius: 6\n");
    o += QStringLiteral("menu.items.bg.color: %1\n").arg(surface);
    o += QStringLiteral("menu.items.text.color: %1\n").arg(surfaceText);
    o += QStringLiteral("menu.items.active.bg.color: %1\n").arg(accent);
    o += QStringLiteral("menu.items.active.text.color: %1\n").arg(activeText);
    o += QStringLiteral("osd.bg.color: %1\n").arg(surface);
    o += QStringLiteral("osd.border.color: %1\n").arg(accent);
    o += QStringLiteral("osd.label.text.color: %1\n").arg(surfaceText);
    return o;
}

ThemeSpec parseThemeArgs(const QStringList &args) {
    ThemeSpec s;
    for (const QString &a : args) {
        if (a == QLatin1String("--dark"))
            s.dark = true;
        else if (a == QLatin1String("--light"))
            s.dark = false;
        else if (a.startsWith(QLatin1String("--accent=")))
            s.accent = a.section(QLatin1Char('='), 1);
        else if (a.startsWith(QLatin1String("--gtk-theme=")))
            s.gtkTheme = a.section(QLatin1Char('='), 1);
        else if (a.startsWith(QLatin1String("--icon-theme=")))
            s.iconTheme = a.section(QLatin1Char('='), 1);
    }
    return s;
}

static bool writeText(const QString &path, const QString &text) {
    QDir().mkpath(QFileInfo(path).absolutePath());
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;
    return f.write(text.toUtf8()) >= 0;
}

QStringList applyTheme(const ThemeSpec &s, bool persistAppearance) {
    const QString base = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    const QString gtk = gtkSettingsIni(s);
    QStringList written;

    for (const QString &ver : {QStringLiteral("gtk-3.0"), QStringLiteral("gtk-4.0")}) {
        const QString path = base + QLatin1Char('/') + ver + QStringLiteral("/settings.ini");
        if (writeText(path, gtk))
            written << path;
    }

    // HeDE's own palette (read by the shell via Config). Skipped when the accent
    // is world-derived, so a world switch isn't frozen as an explicit choice.
    if (persistAppearance) {
        const QString hede = base + QStringLiteral("/hede/hede.conf");
        QDir().mkpath(QFileInfo(hede).absolutePath());
        QSettings conf(hede, QSettings::IniFormat);
        conf.setValue(QStringLiteral("appearance/dark"), s.dark);
        if (!s.accent.isEmpty())
            conf.setValue(QStringLiteral("appearance/accent"), s.accent);
        conf.sync();
        if (conf.status() == QSettings::NoError)
            written << hede;
    }

    // The Helm labwc titlebar skin, under $XDG_DATA_HOME so it shadows the
    // system default in /usr/share/themes. labwc re-reads it on --reconfigure.
    const QString dataBase = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation);
    const QString themerc = dataBase + QStringLiteral("/themes/Helm/labwc/themerc");
    if (writeText(themerc, themercBody(s)))
        written << themerc;

    return written;
}

bool setWorld(const QString &id) {
    if (!loadWorld(id).valid())
        return false; // no such installed world — leave everything as-is

    const QString base = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    const QString hede = base + QStringLiteral("/hede/hede.conf");
    QDir().mkpath(QFileInfo(hede).absolutePath());
    {
        QSettings conf(hede, QSettings::IniFormat);
        conf.setValue(QStringLiteral("world/id"), id);
        conf.remove(QStringLiteral("appearance/accent")); // adopt the world's accent
        conf.sync();
        if (conf.status() != QSettings::NoError)
            return false;
    }
    // Regenerate the window chrome from the now-active world (labwc + GTK).
    applyThemeFromWorld();
    return true;
}

QStringList applyThemeFromWorld() {
    const QString base = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    QSettings conf(base + QStringLiteral("/hede/hede.conf"), QSettings::IniFormat);

    ThemeSpec s;
    s.dark = conf.value(QStringLiteral("appearance/dark")).toBool();
    s.gtkTheme = conf.value(QStringLiteral("appearance/gtk-theme")).toString();
    s.iconTheme = conf.value(QStringLiteral("appearance/icon-theme")).toString();

    // Accent precedence mirrors helm::effectiveAccent: explicit choice, else the
    // active world, else (empty →) themercBody's Harbor default.
    const QString explicitAccent = conf.value(QStringLiteral("appearance/accent")).toString();
    if (!explicitAccent.isEmpty()) {
        s.accent = explicitAccent;
    } else {
        const QString id = conf.value(QStringLiteral("world/id"), QStringLiteral("harbor")).toString();
        s.accent = loadWorld(id).accent;
    }
    return applyTheme(s, /*persistAppearance=*/false);
}

} // namespace helm
